"""
Integration platform tools for the ServiceNow MCP server.

Covers outbound REST messages (sys_rest_message / sys_rest_message_fn),
Scripted REST APIs (sys_ws_definition / sys_ws_operation), Import Sets
(sys_import_set), and MID Servers (ecc_agent).

Key platform notes:
- sys_rest_message_fn stores http_method as LOWERCASE (get, post, put, patch, delete).
- sys_ws_operation stores http_method as UPPERCASE (GET, POST, PUT, PATCH, DELETE).
- Creating a sys_rest_message record causes the platform to auto-generate a default
  GET HTTP method entry in sys_rest_message_fn.
- The namespace for sys_ws_definition is auto-generated by the platform on insert.
"""

import logging
from typing import Any, Dict, List, Optional

import requests
from pydantic import BaseModel, Field, field_validator, model_validator

from servicenow_mcp.auth.auth_manager import AuthManager
from servicenow_mcp.utils.config import ServerConfig

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Parameter models
# ---------------------------------------------------------------------------


class ListRestMessagesParams(BaseModel):
    """Parameters for listing outbound REST messages."""

    limit: int = Field(10, description="Maximum number of records to return")
    offset: int = Field(0, description="Pagination offset")
    name_filter: Optional[str] = Field(None, description="Filter by name (LIKE match)")


class GetRestMessageParams(BaseModel):
    """Parameters for retrieving a single REST message with its HTTP methods.

    At least one of message_name or message_sys_id must be provided.
    """

    message_name: Optional[str] = Field(None, description="Name of the REST message")
    message_sys_id: Optional[str] = Field(None, description="sys_id of the REST message")

    @model_validator(mode="after")
    def require_at_least_one(self) -> "GetRestMessageParams":
        if not self.message_name and not self.message_sys_id:
            raise ValueError("At least one of message_name or message_sys_id must be provided")
        return self


class CreateRestMessageParams(BaseModel):
    """Parameters for creating an outbound REST message.

    Note: the platform automatically creates a default GET HTTP method entry
    (sys_rest_message_fn) immediately after the sys_rest_message record is inserted.
    """

    name: str = Field(..., description="Unique name for the REST message")
    endpoint: str = Field(..., description="Base endpoint URL")
    description: Optional[str] = Field(None, description="Human-readable description")
    authentication_type: Optional[str] = Field(
        "none", description="Authentication type (e.g. 'none', 'basic', 'oauth2')"
    )


class AddHttpMethodParams(BaseModel):
    """Parameters for adding an HTTP method to an existing REST message.

    Note: http_method is stored as LOWERCASE in sys_rest_message_fn
    (e.g. 'get', 'post', 'put', 'patch', 'delete').
    """

    rest_message_sys_id: str = Field(..., description="sys_id of the parent REST message")
    function_name: str = Field(..., description="Unique function name for this HTTP method")
    http_method: str = Field(
        ..., description="HTTP method in lowercase: get, post, put, patch, delete"
    )
    endpoint: Optional[str] = Field(
        None, description="Override endpoint (relative or absolute). Inherits from parent if omitted."
    )
    content: Optional[str] = Field(None, description="Request body content / template")


class ListScriptedRestApisParams(BaseModel):
    """Parameters for listing Scripted REST API definitions."""

    limit: int = Field(10, description="Maximum number of records to return")
    offset: int = Field(0, description="Pagination offset")
    name_filter: Optional[str] = Field(None, description="Filter by name (LIKE match)")
    active: Optional[bool] = Field(None, description="Filter by active status")


class GetScriptedRestApiParams(BaseModel):
    """Parameters for retrieving a single Scripted REST API with its resources.

    At least one of api_name or api_sys_id must be provided.
    """

    api_name: Optional[str] = Field(None, description="Name of the Scripted REST API")
    api_sys_id: Optional[str] = Field(None, description="sys_id of the Scripted REST API")

    @model_validator(mode="after")
    def require_at_least_one(self) -> "GetScriptedRestApiParams":
        if not self.api_name and not self.api_sys_id:
            raise ValueError("At least one of api_name or api_sys_id must be provided")
        return self


class CreateScriptedRestApiParams(BaseModel):
    """Parameters for creating a Scripted REST API definition.

    Note: the platform auto-generates the namespace (API ID) on insert.
    Provide a unique, URL-safe base_api_path.
    """

    name: str = Field(..., description="Display name of the Scripted REST API")
    base_api_path: str = Field(..., description="Base API path used in the URL (URL-safe)")
    description: Optional[str] = Field(None, description="Human-readable description")
    active: bool = Field(True, description="Whether the API is active")


class AddRestResourceParams(BaseModel):
    """Parameters for adding a resource (operation) to a Scripted REST API.

    Note: http_method is stored as UPPERCASE in sys_ws_operation
    (e.g. 'GET', 'POST', 'PUT', 'PATCH', 'DELETE').
    This differs from sys_rest_message_fn which uses lowercase.
    """

    api_sys_id: str = Field(..., description="sys_id of the parent Scripted REST API (sys_ws_definition)")
    name: str = Field(..., description="Display name for this resource/operation")
    http_method: str = Field(
        ..., description="HTTP method in UPPERCASE: GET, POST, PUT, PATCH, DELETE"
    )
    relative_path: Optional[str] = Field(
        "", description="Relative path appended to the base API path (e.g. '/{id}')"
    )
    script: Optional[str] = Field(None, description="Server-side script implementing the resource")


class ListImportSetsParams(BaseModel):
    """Parameters for listing import sets."""

    limit: int = Field(10, description="Maximum number of records to return")
    offset: int = Field(0, description="Pagination offset")
    state_filter: Optional[str] = Field(None, description="Filter by state (e.g. 'loaded', 'complete')")


class ListMidServersParams(BaseModel):
    """Parameters for listing MID servers."""

    limit: int = Field(10, description="Maximum number of records to return")
    offset: int = Field(0, description="Pagination offset")
    status_filter: Optional[str] = Field(
        None, description="Filter by status (e.g. 'Up', 'Down', 'Unknown')"
    )


class GetMidServerStatusParams(BaseModel):
    """Parameters for retrieving detailed status for a single MID server.

    At least one of server_name or server_sys_id must be provided.
    """

    server_name: Optional[str] = Field(None, description="Name of the MID server")
    server_sys_id: Optional[str] = Field(None, description="sys_id of the MID server")

    @model_validator(mode="after")
    def require_at_least_one(self) -> "GetMidServerStatusParams":
        if not self.server_name and not self.server_sys_id:
            raise ValueError("At least one of server_name or server_sys_id must be provided")
        return self


# ---------------------------------------------------------------------------
# Tool functions
# ---------------------------------------------------------------------------


def list_rest_messages(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: ListRestMessagesParams,
) -> Dict[str, Any]:
    """List outbound REST message definitions from sys_rest_message."""
    try:
        url = f"{config.instance_url}/api/now/table/sys_rest_message"
        headers = auth_manager.get_headers()
        query_params: Dict[str, Any] = {
            "sysparm_limit": params.limit,
            "sysparm_offset": params.offset,
        }
        if params.name_filter:
            query_params["sysparm_query"] = f"nameLIKE{params.name_filter}"

        response = requests.get(url, headers=headers, params=query_params)
        response.raise_for_status()
        items = response.json().get("result", [])
        return {
            "success": True,
            "message": f"Found {len(items)} REST message(s)",
            "rest_messages": items,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error listing REST messages: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error listing REST messages: {e}")
        return {"success": False, "message": f"Error: {e}"}


def get_rest_message(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: GetRestMessageParams,
) -> Dict[str, Any]:
    """Retrieve a single REST message and its associated HTTP methods.

    Performs two requests:
    1. GET sys_rest_message (by name or sys_id) to fetch the parent record.
    2. GET sys_rest_message_fn filtered by the parent's sys_id.
    """
    try:
        headers = auth_manager.get_headers()

        # Step 1: resolve the REST message record
        msg_url = f"{config.instance_url}/api/now/table/sys_rest_message"
        if params.message_sys_id:
            query_params: Dict[str, Any] = {
                "sysparm_query": f"sys_id={params.message_sys_id}",
                "sysparm_limit": 1,
            }
        else:
            query_params = {
                "sysparm_query": f"name={params.message_name}",
                "sysparm_limit": 1,
            }

        msg_response = requests.get(msg_url, headers=headers, params=query_params)
        msg_response.raise_for_status()
        messages = msg_response.json().get("result", [])
        if not messages:
            return {"success": False, "message": "REST message not found"}

        message = messages[0]
        sys_id = message.get("sys_id", "")

        # Step 2: fetch HTTP methods for this message
        fn_url = f"{config.instance_url}/api/now/table/sys_rest_message_fn"
        fn_response = requests.get(
            fn_url,
            headers=headers,
            params={"sysparm_query": f"rest_message={sys_id}"},
        )
        fn_response.raise_for_status()
        http_methods = fn_response.json().get("result", [])

        return {
            "success": True,
            "message": f"Found REST message with {len(http_methods)} HTTP method(s)",
            "message_record": message,
            "http_methods": http_methods,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error fetching REST message: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error fetching REST message: {e}")
        return {"success": False, "message": f"Error: {e}"}


def create_rest_message(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: CreateRestMessageParams,
) -> Dict[str, Any]:
    """Create a new outbound REST message definition in sys_rest_message.

    After creation, the platform automatically inserts a default GET HTTP method
    record in sys_rest_message_fn. Use add_http_method to add additional methods.
    """
    try:
        url = f"{config.instance_url}/api/now/table/sys_rest_message"
        headers = auth_manager.get_headers()
        payload = {k: v for k, v in params.model_dump().items() if v is not None}
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        result = response.json().get("result", {})
        return {
            "success": True,
            "message": f"Created REST message '{params.name}'",
            "item": result,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error creating REST message: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error creating REST message: {e}")
        return {"success": False, "message": f"Error: {e}"}


def add_http_method(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: AddHttpMethodParams,
) -> Dict[str, Any]:
    """Add an HTTP method function to an existing REST message (sys_rest_message_fn).

    The http_method value is stored as lowercase in sys_rest_message_fn
    (e.g. 'get', 'post', 'put', 'patch', 'delete').
    """
    try:
        url = f"{config.instance_url}/api/now/table/sys_rest_message_fn"
        headers = auth_manager.get_headers()
        payload: Dict[str, Any] = {
            "rest_message": params.rest_message_sys_id,
            "function_name": params.function_name,
            "http_method": params.http_method.lower(),
        }
        if params.endpoint is not None:
            payload["http_path"] = params.endpoint
        if params.content is not None:
            payload["content"] = params.content

        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        result = response.json().get("result", {})
        return {
            "success": True,
            "message": f"Added HTTP method '{params.function_name}' to REST message",
            "item": result,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error adding HTTP method: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error adding HTTP method: {e}")
        return {"success": False, "message": f"Error: {e}"}


def list_scripted_rest_apis(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: ListScriptedRestApisParams,
) -> Dict[str, Any]:
    """List Scripted REST API definitions from sys_ws_definition."""
    try:
        url = f"{config.instance_url}/api/now/table/sys_ws_definition"
        headers = auth_manager.get_headers()
        query_params: Dict[str, Any] = {
            "sysparm_limit": params.limit,
            "sysparm_offset": params.offset,
        }
        query_parts: List[str] = []
        if params.name_filter:
            query_parts.append(f"nameLIKE{params.name_filter}")
        if params.active is not None:
            query_parts.append(f"active={'true' if params.active else 'false'}")
        if query_parts:
            query_params["sysparm_query"] = "^".join(query_parts)

        response = requests.get(url, headers=headers, params=query_params)
        response.raise_for_status()
        items = response.json().get("result", [])
        return {
            "success": True,
            "message": f"Found {len(items)} Scripted REST API(s)",
            "scripted_rest_apis": items,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error listing Scripted REST APIs: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error listing Scripted REST APIs: {e}")
        return {"success": False, "message": f"Error: {e}"}


def get_scripted_rest_api(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: GetScriptedRestApiParams,
) -> Dict[str, Any]:
    """Retrieve a single Scripted REST API definition with its resources/operations.

    Performs two requests:
    1. GET sys_ws_definition (by name or sys_id).
    2. GET sys_ws_operation filtered by the parent's sys_id.

    Note: sys_ws_operation.http_method is stored as UPPERCASE (GET, POST, PUT...).
    """
    try:
        headers = auth_manager.get_headers()
        api_url = f"{config.instance_url}/api/now/table/sys_ws_definition"

        if params.api_sys_id:
            query_params: Dict[str, Any] = {
                "sysparm_query": f"sys_id={params.api_sys_id}",
                "sysparm_limit": 1,
            }
        else:
            query_params = {
                "sysparm_query": f"name={params.api_name}",
                "sysparm_limit": 1,
            }

        api_response = requests.get(api_url, headers=headers, params=query_params)
        api_response.raise_for_status()
        apis = api_response.json().get("result", [])
        if not apis:
            return {"success": False, "message": "Scripted REST API not found"}

        api_record = apis[0]
        sys_id = api_record.get("sys_id", "")

        # Fetch operations/resources
        ops_url = f"{config.instance_url}/api/now/table/sys_ws_operation"
        ops_response = requests.get(
            ops_url,
            headers=headers,
            params={"sysparm_query": f"web_service_definition={sys_id}"},
        )
        ops_response.raise_for_status()
        operations = ops_response.json().get("result", [])

        return {
            "success": True,
            "message": f"Found Scripted REST API with {len(operations)} resource(s)",
            "api_record": api_record,
            "operations": operations,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error fetching Scripted REST API: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error fetching Scripted REST API: {e}")
        return {"success": False, "message": f"Error: {e}"}


def create_scripted_rest_api(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: CreateScriptedRestApiParams,
) -> Dict[str, Any]:
    """Create a new Scripted REST API definition in sys_ws_definition.

    The platform auto-generates the namespace (API ID) on insert.
    Provide a unique, URL-safe value for base_api_path.
    """
    try:
        url = f"{config.instance_url}/api/now/table/sys_ws_definition"
        headers = auth_manager.get_headers()
        payload = {k: v for k, v in params.model_dump().items() if v is not None}
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        result = response.json().get("result", {})
        return {
            "success": True,
            "message": f"Created Scripted REST API '{params.name}'",
            "item": result,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error creating Scripted REST API: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error creating Scripted REST API: {e}")
        return {"success": False, "message": f"Error: {e}"}


def add_rest_resource(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: AddRestResourceParams,
) -> Dict[str, Any]:
    """Add a resource (operation) to a Scripted REST API in sys_ws_operation.

    Note: http_method is stored as UPPERCASE in sys_ws_operation (e.g. 'GET', 'POST').
    This differs from sys_rest_message_fn which uses lowercase.
    """
    try:
        url = f"{config.instance_url}/api/now/table/sys_ws_operation"
        headers = auth_manager.get_headers()
        payload: Dict[str, Any] = {
            "web_service_definition": params.api_sys_id,
            "name": params.name,
            "http_method": params.http_method.upper(),
            "relative_path": params.relative_path or "",
        }
        if params.script is not None:
            payload["operation_script"] = params.script

        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        result = response.json().get("result", {})
        return {
            "success": True,
            "message": f"Added REST resource '{params.name}' to Scripted REST API",
            "item": result,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error adding REST resource: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error adding REST resource: {e}")
        return {"success": False, "message": f"Error: {e}"}


def list_import_sets(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: ListImportSetsParams,
) -> Dict[str, Any]:
    """List import sets from sys_import_set."""
    try:
        url = f"{config.instance_url}/api/now/table/sys_import_set"
        headers = auth_manager.get_headers()
        query_params: Dict[str, Any] = {
            "sysparm_limit": params.limit,
            "sysparm_offset": params.offset,
        }
        if params.state_filter:
            query_params["sysparm_query"] = f"state={params.state_filter}"

        response = requests.get(url, headers=headers, params=query_params)
        response.raise_for_status()
        items = response.json().get("result", [])
        return {
            "success": True,
            "message": f"Found {len(items)} import set(s)",
            "import_sets": items,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error listing import sets: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error listing import sets: {e}")
        return {"success": False, "message": f"Error: {e}"}


def list_mid_servers(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: ListMidServersParams,
) -> Dict[str, Any]:
    """List MID servers from ecc_agent."""
    try:
        url = f"{config.instance_url}/api/now/table/ecc_agent"
        headers = auth_manager.get_headers()
        query_params: Dict[str, Any] = {
            "sysparm_limit": params.limit,
            "sysparm_offset": params.offset,
            "sysparm_fields": "sys_id,name,status,validated,version,host_name,ip_address,last_refreshed",
        }
        if params.status_filter:
            query_params["sysparm_query"] = f"status={params.status_filter}"

        response = requests.get(url, headers=headers, params=query_params)
        response.raise_for_status()
        items = response.json().get("result", [])
        return {
            "success": True,
            "message": f"Found {len(items)} MID server(s)",
            "mid_servers": items,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error listing MID servers: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error listing MID servers: {e}")
        return {"success": False, "message": f"Error: {e}"}


def get_mid_server_status(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: GetMidServerStatusParams,
) -> Dict[str, Any]:
    """Retrieve detailed status for a single MID server from ecc_agent."""
    try:
        url = f"{config.instance_url}/api/now/table/ecc_agent"
        headers = auth_manager.get_headers()

        if params.server_sys_id:
            query_params: Dict[str, Any] = {
                "sysparm_query": f"sys_id={params.server_sys_id}",
                "sysparm_limit": 1,
                "sysparm_fields": "sys_id,name,status,validated,version,host_name,ip_address,last_refreshed,up,error_message",
            }
        else:
            query_params = {
                "sysparm_query": f"name={params.server_name}",
                "sysparm_limit": 1,
                "sysparm_fields": "sys_id,name,status,validated,version,host_name,ip_address,last_refreshed,up,error_message",
            }

        response = requests.get(url, headers=headers, params=query_params)
        response.raise_for_status()
        results = response.json().get("result", [])
        if not results:
            return {"success": False, "message": "MID server not found"}

        server = results[0]
        return {
            "success": True,
            "message": f"Retrieved MID server '{server.get('name', '')}'",
            "server": server,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error fetching MID server status: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error fetching MID server status: {e}")
        return {"success": False, "message": f"Error: {e}"}


# ---------------------------------------------------------------------------
# Transform Maps (sys_transform_map) — Story 8.2
# ---------------------------------------------------------------------------


class ListTransformMapsParams(BaseModel):
    """Parameters for listing transform maps."""

    limit: int = Field(10, description="Maximum number of records to return")
    offset: int = Field(0, description="Pagination offset")
    source_table_filter: Optional[str] = Field(None, description="Filter by source table (LIKE match)")
    active: Optional[bool] = Field(None, description="Filter by active flag")


class CreateTransformMapParams(BaseModel):
    """Parameters for creating a transform map."""

    name: str = Field(..., description="Name of the transform map")
    source_table: str = Field(..., description="Staging table name (source)")
    target_table: str = Field(..., description="Target table name")
    active: bool = Field(True, description="Whether the transform map is active")
    run_business_rules: bool = Field(True, description="Run business rules on target records")
    copy_empty_fields: bool = Field(False, description="Copy fields even when source value is empty")


class RunTransformParams(BaseModel):
    """Parameters for running a transform against an existing import set."""

    import_set_sys_id: str = Field(..., description="sys_id of the import set to transform")
    transform_map_sys_id: Optional[str] = Field(
        None, description="sys_id of a specific transform map to use; omit to run all active maps"
    )


class RunImportParams(BaseModel):
    """Parameters for inserting a row into a staging table and triggering its transform maps."""

    staging_table: str = Field(..., description="Name of the staging/import set table")
    payload: Dict[str, Any] = Field(..., description="Field name to value dict for the staging row")

    @field_validator("staging_table")
    @classmethod
    def validate_staging_table(cls, v: str) -> str:
        import re
        if not re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", v):
            raise ValueError(
                f"staging_table must be a valid ServiceNow table name (alphanumeric + underscore): {v!r}"
            )
        return v


def list_transform_maps(
    config: ServerConfig, auth_manager: AuthManager, params: ListTransformMapsParams
) -> Dict[str, Any]:
    """List transform maps from sys_transform_map."""
    try:
        url = f"{config.instance_url}/api/now/table/sys_transform_map"
        query_parts: List[str] = []
        if params.source_table_filter:
            query_parts.append(f"source_tableLIKE{params.source_table_filter}")
        if params.active is not None:
            query_parts.append(f"active={str(params.active).lower()}")

        request_params: Dict[str, Any] = {
            "sysparm_limit": params.limit,
            "sysparm_offset": params.offset,
            "sysparm_fields": "sys_id,name,source_table,target_table,active,run_business_rules",
        }
        if query_parts:
            request_params["sysparm_query"] = "^".join(query_parts)

        response = requests.get(url, headers=auth_manager.get_headers(), params=request_params)
        response.raise_for_status()
        data = response.json().get("result", [])
        return {"success": True, "count": len(data), "transform_maps": data, "message": f"Found {len(data)} transform map(s)"}
    except requests.HTTPError as e:
        logger.error(f"HTTP error listing transform maps: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error listing transform maps: {e}")
        return {"success": False, "message": f"Error: {e}"}


def create_transform_map(
    config: ServerConfig, auth_manager: AuthManager, params: CreateTransformMapParams
) -> Dict[str, Any]:
    """Create a new transform map on sys_transform_map."""
    try:
        url = f"{config.instance_url}/api/now/table/sys_transform_map"
        payload = {
            "name": params.name,
            "source_table": params.source_table,
            "target_table": params.target_table,
            "active": params.active,
            "run_business_rules": params.run_business_rules,
            "copy_empty_fields": params.copy_empty_fields,
        }
        response = requests.post(url, headers=auth_manager.get_headers(), json=payload)
        response.raise_for_status()
        record = response.json().get("result", {})
        return {"success": True, "message": f"Transform map '{params.name}' created", "transform_map": record}
    except requests.HTTPError as e:
        logger.error(f"HTTP error creating transform map '{params.name}': {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error creating transform map '{params.name}': {e}")
        return {"success": False, "message": f"Error: {e}"}


def run_transform(
    config: ServerConfig, auth_manager: AuthManager, params: RunTransformParams
) -> Dict[str, Any]:
    """Trigger transform map processing for an existing import set.

    Creates a sys_import_set_run record that causes the ServiceNow scheduler
    to process the specified import set through the given transform map.
    """
    try:
        url = f"{config.instance_url}/api/now/table/sys_import_set_run"
        payload: Dict[str, Any] = {
            "import_set": params.import_set_sys_id,
        }
        if params.transform_map_sys_id:
            payload["transform_map"] = params.transform_map_sys_id
        response = requests.post(url, headers=auth_manager.get_headers(), json=payload)
        response.raise_for_status()
        return {"success": True, "message": "Transform run queued", "result": response.json().get("result", {})}
    except requests.HTTPError as e:
        logger.error(f"HTTP error running transform for import set {params.import_set_sys_id}: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error running transform for import set {params.import_set_sys_id}: {e}")
        return {"success": False, "message": f"Error: {e}"}


def run_import(
    config: ServerConfig, auth_manager: AuthManager, params: RunImportParams
) -> Dict[str, Any]:
    """Insert a row into a staging table and trigger its transform maps.

    Uses the ServiceNow Import Set API: POST /api/now/import/{staging_table}
    This inserts the row and automatically runs all active transform maps.
    Returns per-target-row transform results.
    """
    url = f"{config.instance_url}/api/now/import/{params.staging_table}"
    try:
        response = requests.post(url, headers=auth_manager.get_headers(), json=params.payload)
        response.raise_for_status()
        result = response.json().get("result", [])
        if isinstance(result, dict):
            result = [result]
        return {"success": True, "count": len(result), "results": result, "message": f"Import completed: {len(result)} row(s) processed"}
    except requests.HTTPError as e:
        logger.error(f"HTTP error running import for table {params.staging_table}: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error running import for table {params.staging_table}: {e}")
        return {"success": False, "message": f"Error: {e}"}
