"""
Integration platform tools for the ServiceNow MCP server.

Provides compound inspection tools for outbound REST messages and Scripted REST APIs.
Each tool fetches a parent record plus its child records in a single logical operation.

Simple CRUD for integration tables (sys_rest_message, sys_ws_definition, sys_import_set,
ecc_agent, sys_transform_map) is handled by table_tools (query_records, get_record,
create_record, update_record, delete_record) using the integration architecture blueprint.

Key platform notes:
- sys_rest_message_fn stores http_method as LOWERCASE (get, post, put, patch, delete).
- sys_ws_operation stores http_method as UPPERCASE (GET, POST, PUT, PATCH, DELETE).
- Creating a sys_rest_message record causes the platform to auto-generate a default
  GET HTTP method entry in sys_rest_message_fn.
- The namespace for sys_ws_definition is auto-generated by the platform on insert.
"""

import logging
from typing import Any, Dict, Optional

import requests
from pydantic import BaseModel, Field, model_validator

from servicenow_mcp.auth.auth_manager import AuthManager
from servicenow_mcp.utils.config import ServerConfig

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Parameter models
# ---------------------------------------------------------------------------


class GetRestMessageParams(BaseModel):
    """Parameters for retrieving a single REST message with its HTTP methods.

    At least one of message_name or message_sys_id must be provided.
    """

    message_name: Optional[str] = Field(None, description="Name of the REST message")
    message_sys_id: Optional[str] = Field(None, description="sys_id of the REST message")

    @model_validator(mode="after")
    def require_at_least_one(self) -> "GetRestMessageParams":
        if not self.message_name and not self.message_sys_id:
            raise ValueError("At least one of message_name or message_sys_id must be provided")
        return self


class GetScriptedRestApiParams(BaseModel):
    """Parameters for retrieving a single Scripted REST API with its resources.

    At least one of api_name or api_sys_id must be provided.
    """

    api_name: Optional[str] = Field(None, description="Name of the Scripted REST API")
    api_sys_id: Optional[str] = Field(None, description="sys_id of the Scripted REST API")

    @model_validator(mode="after")
    def require_at_least_one(self) -> "GetScriptedRestApiParams":
        if not self.api_name and not self.api_sys_id:
            raise ValueError("At least one of api_name or api_sys_id must be provided")
        return self


# ---------------------------------------------------------------------------
# Tool functions
# ---------------------------------------------------------------------------


def get_rest_message(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: GetRestMessageParams,
) -> Dict[str, Any]:
    """Retrieve a single REST message and its associated HTTP methods.

    Performs two requests:
    1. GET sys_rest_message (by name or sys_id) to fetch the parent record.
    2. GET sys_rest_message_fn filtered by the parent's sys_id.
    """
    try:
        headers = auth_manager.get_headers()

        # Step 1: resolve the REST message record
        msg_url = f"{config.instance_url}/api/now/table/sys_rest_message"
        if params.message_sys_id:
            query_params: Dict[str, Any] = {
                "sysparm_query": f"sys_id={params.message_sys_id}",
                "sysparm_limit": 1,
            }
        else:
            query_params = {
                "sysparm_query": f"name={params.message_name}",
                "sysparm_limit": 1,
            }

        msg_response = requests.get(msg_url, headers=headers, params=query_params)
        msg_response.raise_for_status()
        messages = msg_response.json().get("result", [])
        if not messages:
            return {"success": False, "message": "REST message not found"}

        message = messages[0]
        sys_id = message.get("sys_id", "")

        # Step 2: fetch HTTP methods for this message
        fn_url = f"{config.instance_url}/api/now/table/sys_rest_message_fn"
        fn_response = requests.get(
            fn_url,
            headers=headers,
            params={"sysparm_query": f"rest_message={sys_id}"},
        )
        fn_response.raise_for_status()
        http_methods = fn_response.json().get("result", [])

        return {
            "success": True,
            "message": f"Found REST message with {len(http_methods)} HTTP method(s)",
            "message_record": message,
            "http_methods": http_methods,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error fetching REST message: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error fetching REST message: {e}")
        return {"success": False, "message": f"Error: {e}"}


def get_scripted_rest_api(
    config: ServerConfig,
    auth_manager: AuthManager,
    params: GetScriptedRestApiParams,
) -> Dict[str, Any]:
    """Retrieve a single Scripted REST API definition with its resources/operations.

    Performs two requests:
    1. GET sys_ws_definition (by name or sys_id).
    2. GET sys_ws_operation filtered by the parent's sys_id.

    Note: sys_ws_operation.http_method is stored as UPPERCASE (GET, POST, PUT...).
    """
    try:
        headers = auth_manager.get_headers()
        api_url = f"{config.instance_url}/api/now/table/sys_ws_definition"

        if params.api_sys_id:
            query_params: Dict[str, Any] = {
                "sysparm_query": f"sys_id={params.api_sys_id}",
                "sysparm_limit": 1,
            }
        else:
            query_params = {
                "sysparm_query": f"name={params.api_name}",
                "sysparm_limit": 1,
            }

        api_response = requests.get(api_url, headers=headers, params=query_params)
        api_response.raise_for_status()
        apis = api_response.json().get("result", [])
        if not apis:
            return {"success": False, "message": "Scripted REST API not found"}

        api_record = apis[0]
        sys_id = api_record.get("sys_id", "")

        # Fetch operations/resources
        ops_url = f"{config.instance_url}/api/now/table/sys_ws_operation"
        ops_response = requests.get(
            ops_url,
            headers=headers,
            params={"sysparm_query": f"web_service_definition={sys_id}"},
        )
        ops_response.raise_for_status()
        operations = ops_response.json().get("result", [])

        return {
            "success": True,
            "message": f"Found Scripted REST API with {len(operations)} resource(s)",
            "api_record": api_record,
            "operations": operations,
        }
    except requests.HTTPError as e:
        logger.error(f"HTTP error fetching Scripted REST API: {e}")
        return {"success": False, "message": f"HTTP error: {e}"}
    except Exception as e:
        logger.error(f"Error fetching Scripted REST API: {e}")
        return {"success": False, "message": f"Error: {e}"}
